---
- name: "Synchronous #1"
  hosts: nodes[0:2] # 3 nodes
  tasks:
    - name: Task 1
      command: sleep 30

    - name: Task 2
      command: sleep 5

    - name: Task 3
      command: sleep 5

    - name: Task 4
      command: sleep 5

    - name: Task 5
      command: sleep 5
